SKIN_TONE_MODEL = "models/skin_tone_model.pth"
FACE_SHAPE_MODEL = "models/face_shape_model.pth"
BODY_TYPE_MODEL = "models/body_type_model.pth"
HAIR_TYPE_MODEL = "models/hair_type_model.pth"
BALD_MODEL = "models/bald_model.pth"